services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Components\Api\Controller\ProductController: ~
    App\Components\Api\Controller\CategoryController: ~
    App\Components\Admin\Repository\CategoryRepository: ~
    App\Components\Admin\Repository\ProductRepository: ~
